import Hero from "./Sections/Hero";
import Navbar from "./Navbar";
import Client from "./Sections/Client";
import About from "./Sections/About";
import HowItWorks from "./Sections/HowItWorks";
import Service from "./Sections/Service";
import CTA from "./Sections/CTA";
import GIC from "./Sections/GIC";
import Footer from "./Sections/Footer";
export { Footer, GIC, CTA, Service, About, Hero, Navbar, Client, HowItWorks };
